version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    env_file: ./.env
    container_name: mysqldb
    environment:
      - MYSQL_ROOT_PASSWORD=wREobe6BtzUN.0UZ
      - MYSQL_DATABASE=melochord
      - MYSQL_USER=user1
      - MYSQL_PASSWORD=wREobe6BtzUN.0UZ
    restart: always
    ports:
      - 3306:3306
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

  loginservice:
    depends_on:
      - mysqldb
    build:
      context: ./server
      dockerfile: ./Dockerfile
    container_name: loginservice
    restart: on-failure
    env_file: ./.env
    volumes:
      - ./server:/server
    ports:
      - 3001:3001
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=3306
    extra_hosts:
      - localhost:127.0.0.1
      - host.docker.internal:172.26.0.3
    networks:
      - backend
      - frontend
        

volumes: 
  db:

networks:
  backend:
  frontend:
    name: frontend
    external: true
