version: '3.8'

services:
  mysqldb:
    image: mysql:8.0
    build: ./mysqldb
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
    restart: always
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
    networks:
      - backend

     

  loginservice:
    depends_on:
      - mysqldb
    build: ./loginservice
    restart: unless-stopped
    env_file: ./.env
    volumes:
      - loginservice:/loginservice
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    environment:
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_PASSWORD
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_HOST=mysqldb
      - MYSQL_PORT=$MYSQLDB_LOCAL_PORT
    extra_hosts:
      - "localhost:127.0.0.1"    
    networks:
      - backend
      - frontend

volumes: 
  db:
  loginservice:

networks:
  backend:
  frontend:
